version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongoexpress:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb


# Above configuration is substitution of below docker run command

#docker run -d \
#-p27017:27017 \
#-e MONGO_INITDB_ROOT_USERNAME=admin \
#-e MONGO_INITDB_ROOT_PASSWORD=password \
#--name mongo-db \
#--net mongo-network \
#mongo

#     &&&&&&&&&&&&&&&&&&&&&&&&&&&&

#docker run -d \
#-p 8081:8081 \
#-e ME_CONFIG_MONGODB_ADMINUSERNAME=admin \
#-e ME_CONFIG_MONGODB_ADMINPASSWORD=password \
#--net mongo-network \
# --name mongo-express \
# -e ME_CONFIG_MONGODB_SERVER=mongo-db \
# mongo-express